version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: homeguard
    binary: homeguard
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: homeguard
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - README_ZH.md
      - LICENSE
      - config.example.yaml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  abbrev: 7
  
  # 格式：- hash: message (@username)
  # .SHA - commit hash
  # .Message - 提交信息第一行
  # .AuthorUsername - GitHub 用户名（需要 use: github）
  format: "- {{.SHA}}: {{.Message}}"
  
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other Changes"
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: p3ddd
    name: HomeGuard

  # 隐私保护：先生成草稿，审查后再手动发布
  draft: true
  replace_existing_draft: true

  prerelease: auto
  make_latest: true

  name_template: "{{.ProjectName}}-v{{.Version}}"
