version: '3'

vars:
  SERVER_BINARY: homeguard
  CLIENT_BINARY: wolctl
  INSTALL_PATH: /usr/local/bin
  LDFLAGS: -s -w

tasks:
  default:
    desc: Build the application (server and client)
    cmds:
      - task: build

  build:
    desc: Build both server and client
    deps:
      - build:server
      - build:client

  build:server:
    desc: Build the server binary
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.SERVER_BINARY}}"
    cmds:
      - echo "Building {{.SERVER_BINARY}}..."
      - go build -ldflags="{{.LDFLAGS}}" -o {{.SERVER_BINARY}} .
      - echo "✓ Server build complete!"

  build:client:
    desc: Build the client tool
    sources:
      - "cmd/wolctl/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.CLIENT_BINARY}}"
    cmds:
      - echo "Building {{.CLIENT_BINARY}}..."
      - go build -ldflags="{{.LDFLAGS}}" -o {{.CLIENT_BINARY}} ./cmd/wolctl/
      - echo "✓ Client build complete!"

  run:
    desc: Run the server application
    cmds:
      - echo "Running {{.SERVER_BINARY}}..."
      - go run main.go

  clean:
    desc: Clean build files and artifacts
    cmds:
      - echo "Cleaning build artifacts..."
      - go clean
      - rm -f {{.SERVER_BINARY}} {{.CLIENT_BINARY}}
      - rm -rf dist/ build/
      - echo "✓ Clean complete!"

  test:
    desc: Run tests
    cmds:
      - echo "Running tests..."
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - echo "✓ Tests complete!"

  test:short:
    desc: Run tests without race detector
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests and show coverage
    cmds:
      - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "✓ Coverage report generated: coverage.html"

  lint:
    desc: Run linter
    cmds:
      - echo "Running linter..."
      - golangci-lint run
      - echo "✓ Lint complete!"

  fmt:
    desc: Format code
    cmds:
      - echo "Formatting code..."
      - go fmt ./...
      - goimports -w .
      - echo "✓ Format complete!"

  tidy:
    desc: Tidy go.mod
    cmds:
      - echo "Tidying go.mod..."
      - go mod tidy
      - echo "✓ Tidy complete!"

  install:
    desc: Install binaries to system
    deps:
      - build
    cmds:
      - echo "Installing {{.SERVER_BINARY}} and {{.CLIENT_BINARY}} to {{.INSTALL_PATH}}..."
      - cp {{.SERVER_BINARY}} {{.INSTALL_PATH}}/
      - cp {{.CLIENT_BINARY}} {{.INSTALL_PATH}}/
      - echo "✓ Install complete!"

  uninstall:
    desc: Uninstall binaries from system
    cmds:
      - echo "Uninstalling {{.SERVER_BINARY}} and {{.CLIENT_BINARY}}..."
      - rm -f {{.INSTALL_PATH}}/{{.SERVER_BINARY}}
      - rm -f {{.INSTALL_PATH}}/{{.CLIENT_BINARY}}
      - echo "✓ Uninstall complete!"

  config:
    desc: Create config from example
    cmds:
      - |
        if [ ! -f config.yaml ]; then
          cp config.example.yaml config.yaml
          echo "✓ Created config.yaml from example"
        else
          echo "⚠ config.yaml already exists"
        fi

  dev:
    desc: Run in development mode with auto-reload
    cmds:
      - echo "Starting development server..."
      - air

  docker:build:
    desc: Build Docker image
    cmds:
      - echo "Building Docker image..."
      - docker build -t homeguard:latest .
      - echo "✓ Docker image built!"

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run --rm --network host -v $(pwd)/devices.yaml:/app/devices.yaml:ro homeguard:latest

  docker:up:
    desc: Start Docker Compose services
    cmds:
      - docker-compose up -d
      - echo "✓ Services started!"

  docker:down:
    desc: Stop Docker Compose services
    cmds:
      - docker-compose down
      - echo "✓ Services stopped!"

  release:
    desc: Create a release build
    cmds:
      - echo "Creating release build..."
      - goreleaser release --clean
      - echo "✓ Release complete!"

  release:snapshot:
    desc: Create a snapshot release (no push)
    cmds:
      - echo "Creating snapshot release..."
      - goreleaser release --snapshot --clean
      - echo "✓ Snapshot release complete!"

  all:
    desc: Run all checks (fmt, lint, test, build)
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build

  ci:
    desc: Run CI checks
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: test
      - task: build

